### PR TITLE
Added the game list updated from SwitchBrew

### PR DESCRIPTION
**Pull request by devtekve**
Hey, this is just the first version tho, If you like it we can keep working on it. I would like to port this to .net core (instead of mono), keep in mind this is the MVP, so I didnt focus too much on the best coding practices but in something useful :)

Let me know if you like it and we go from there!.
image
https://i.gyazo.com/b1fe8d66fcc6214c32c406022b950f2d.mp4

### CODE REVIEW

**Review by DeltaJordan — CHANGES_REQUESTED** [review]
For organization I think it would be best to keep the .Net Core project to a separate pull request.

**Comment by devtekve** [comment]
@JordanZeotni, I am agreee that in its current state it shouldn't be there (I will remove it from this commit), however, for the future, I believe we should provide console (Net core) and UI, what do you think?
Also, SwitchbrewWrapper is in .net standard 2.0 if you didn't notice, so it is usable anywhere.

**Comment by devtekve** [comment]
@JordanZeotni I would believe that because it is .net standard, Appveyor is failing. 
(I am using nuget packages, appveyor does not seem to like it, does it?. or maybe is it because it is a .net standard? which I honestly dont think so)

**Review by DeltaJordan — APPROVED** [review]

**Comment by DeltaJordan** [comment]
If we are actually going to maintain this, I would say our first priority will be to move core mechanics, like the HTTPRequests, to a shared project and implementing some of the anti-detection methods used in www.github.com/Reisyukaku/CDNX

**Comment by devtekve** [comment]
@JordanZeotni That was my idea, and the reason I named the DLL HACDN and nothing else, would be nice to have everything properly packed up in the DLL and expose it to make it work virtually anywhere. (as long as we keep it .net standard)

**Pull request merged**
